### PR TITLE
Fixes #RHIROS-1357 - Upgrade to Python 3.11

### PR DESCRIPTION
**Pull request by upadhyeammit**
## Why do we need this change? :thought_balloon:

The [support for Python 3.8 ends on October 2024](https://devguide.python.org/versions/#). Considering this we are upgrading to support Python 3.11

## Documentation update? :memo:

- [ ] Yes
- [ ] No

## Security Checklist :lock:

Upon raising this PR please go through [RedHatInsights/secure-coding-checklist](https://github.com/RedHatInsights/secure-coding-checklist)

## :guardsman: Checklist :dart:

- [ ] Bugfix
- [ ] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added
- [ ] DB Migration Added

## Additional :mega:

Feel free to add any other relevant details such as __links, notes, screenshots__, here.

### CODE REVIEW

**Comment by upadhyeammit** [comment]
> > its failing for librdkafka, I tried to include it however the package is not available in default repository, I would check this further,
> > ```
> > 21:17:25 #14 34.61   In file included from /tmp/tmpnzjmw3jb/confluent-kafka-1.5.0/confluent_kafka/src/Admin.c:17:
> > 21:17:25 #14 34.61   /tmp/tmpnzjmw3jb/confluent-kafka-1.5.0/confluent_kafka/src/confluent_kafka.h:22:10: fatal error: librdkafka/rdkafka.h: No such file or directory
> > 21:17:25 #14 34.61    #include <librdkafka/rdkafka.h>
> > 21:17:25 #14 34.61             ^~~~~~~~~~~~~~~~~~~~~~
> > 21:17:25 #14 34.61   compilation terminated.
> > 21:17:25 #14 34.61   error: command '/usr/bin/gcc' failed with exit code 1
> > 21:17:25 #14 34.61   
> > ```
> 
> This package is not available for EL8 https://access.redhat.com/downloads/content/librdkafka-devel/1.6.1-102.el9/x86_64/fd431d51/package

We need to get [confluent-kafka 2.2.0](https://github.com/confluentinc/confluent-kafka-python/releases/tag/v2.0.2) : https://github.com/confluentinc/confluent-kafka-python/issues/1452

**Review by r14chandra — APPROVED** [review]
Lgtm!

**Comment by r14chandra** [comment]
@yash2189 Could you take a look for testing? Thanks!

**Comment by yash2189** [comment]
Attached the observations from the EE testing on ros-backend on the jira card. We are positive w.r.t our tests :+1:

**Pull request merged**
