### PR TITLE
Refs #RHIROS-757 - upgrade DB used in ephemeral to 13

### PR DESCRIPTION
**Pull request by kgaikwad**

### CODE REVIEW

**Comment by kgaikwad** [comment]
+ adding @ShivamPandya into cc for testing this change in ephemeral env.
Could you please verify if all tests are green with postgresql 13?

**Comment by ShivamPandya** [comment]
Hello @kgaikwad  

I just finished testing on ephemeral environment.

Operations tested :
- Uploading an archive
- Calling /systems end point to check the systems.
- Calling /executive_report end point to see the overall status

Things are working fine with the MR.

**Review by patilsuraj767 — APPROVED** [review]

**Pull request merged**
