### PR TITLE
Refactor - realigned archive files and data json files

### PR DESCRIPTION
**Pull request by kgaikwad**

### CODE REVIEW

**Review by saltgen — COMMENTED** [review]
@kgaikwad I believe we will need to update the file name in the Makefile as well.

Rest of the changes look good to me :+1:

**Comment by kgaikwad** [comment]
> @kgaikwad I believe we will need to update the file name in the Makefile as well.
> 
> Rest of the changes look good to me +1

Good catch!

**Comment by kgaikwad** [comment]
@ShivamPandya / @mayurilahane  - Are there any tests that refer github archive files` paths?

**Comment by kgaikwad** [comment]
@saltgen - Can we get this PR merge?

**Pull request merged**
