### PR TITLE
RHIROS-634 add check for systems with no cloud_provider under suggestions

### PR DESCRIPTION
**Pull request by r14chandra**

### CODE REVIEW

**Review by PreetiW — COMMENTED** [review]
@kgaikwad @r14chandra Since we found the root cause of this, I think this PR is no longer needed. Any thoughts?

**Comment by r14chandra** [comment]
I still see the error on prod

**Comment by r14chandra** [comment]
@PreetiW Root cause you mean kafka consumer?

**Review by kgaikwad — APPROVED** [review]
To avoid 500 errors on API requests, merging this change as a temporary fix.

**Pull request merged**
