### PR TITLE
RHIROS-806 - add indices for various tables

### PR DESCRIPTION
**Pull request by upadhyeammit**
## Why do we need this change? :thought_balloon:

The SQL queries should benefit from explicit indices on the columns which are involved in the queries. As per that I have added the indices and migration.

## Documentation update? :memo:

- [ ] Yes
- [x] No

## Security Checklist :lock:

Upon raising this PR please go through [RedHatInsights/secure-coding-checklist](https://github.com/RedHatInsights/secure-coding-checklist)

## :guardsman: Checklist :dart:

- [ ] Bugfix
- [ ] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added
- [x] DB Migration Added

## Additional :mega:

Feel free to add any other relevant details such as __links, notes, screenshots__, here.

### CODE REVIEW

**Review by saltgen — COMMENTED** [review]
Hey @upadhyeammit :wave: 
Do you think below fields from `System` model might benefit from indexing?

```
inventory_id = db.Column(UUID(as_uuid=True), nullable=False)
operating_system = db.Column(JSONB)
cpu_states = db.Column(db.ARRAY(db.String))
io_states = db.Column(db.ARRAY(db.String))
memory_states = db.Column(db.ARRAY(db.String))
```
The `ExecutiveReportAPI` is currently our heaviest, you may want to take a look at the fields usage on it.

**Comment by upadhyeammit** [comment]
> Hey @upadhyeammit wave Do you think below fields from `System` model might benefit from indexing?
> 
> ```
> inventory_id = db.Column(UUID(as_uuid=True), nullable=False)
> operating_system = db.Column(JSONB)
> cpu_states = db.Column(db.ARRAY(db.String))
> io_states = db.Column(db.ARRAY(db.String))
> memory_states = db.Column(db.ARRAY(db.String))
> ```
> 
> The `ExecutiveReportAPI` is currently our heaviest, you may want to take a look at the fields usage on it.

Below are my findings,

1. The inventory_id is being used for exact match,

https://github.com/RedHatInsights/ros-backend/blob/main/ros/api/common/utils.py#L53

Hence I will add the hash index for same, hash indices were not preferred prior to Postgresql 10 as we have 11.x in production we can use it. More details on this: https://hakibenita.com/postgresql-hash-index

2. I am able to see operating_system in `IN` filter,

https://github.com/RedHatInsights/ros-backend/blob/main/ros/api/v1/hosts.py#L198 so will add btree index for same.

3. However for cpu_states, io_states and memory_states I am unable to find exact queries where adding indices will be helpful.

So would like to know if I am missing something here? @saltgen ?

**Comment by saltgen** [comment]
@upadhyeammit `inventory_id` and `operating_system` sound good :+1: 

Here we are creating an anonymous table using join and then filtering on the same.

https://github.com/RedHatInsights/ros-backend/blob/main/ros/api/v1/hosts.py#L419-L430

Feel free to add indexing on relevant fields if you see fit :v:

**Review by saltgen — APPROVED** [review]
Thanks for the changes @upadhyeammit!

**Pull request merged**
