### PR TITLE
RHIROS-402 | Correction on util data types

### PR DESCRIPTION
**Pull request by saltgen**
### Changes:
1. Explicit convert of cpu, memory to int

### Additional:
* max_io and io dict value types are pending
* Reference: https://github.com/RedHatInsights/ros-backend/pull/150#issuecomment-996115794

### CODE REVIEW

**Review by kgaikwad — CHANGES_REQUESTED** [review]
For `max_io` and IOPS value against each device, let's conside `int` only.

Referring  to - https://en.wikipedia.org/wiki/IOPS, I don't see any IOPS value in float there. 
@saltgen - what do you think?

**Comment by saltgen** [comment]
> For `max_io` and IOPS value against each device, let's conside `int` only.
> 
> Referring to - https://en.wikipedia.org/wiki/IOPS, I don't see any IOPS value in float there. @saltgen - what do you think?

I referred to the same wiki for my conclusion, but from rules I am getting `io` as float, hence when I multiply it by 100
I get float

For instance `"io": {"xvda": 0.314}` will be saved up as 31.4, that said this is **from archive**.

Shall we still go ahead with `int` for  `max_io` and IOPS value?

**Comment by kgaikwad** [comment]
> Shall we still go ahead with `int` for `max_io` and IOPS value?
Yes, it should be `int` for both.

> That said am I using the wrong multiplier i.e. 100. thinking Let me check with Pau
+1 for checking with Pau

**Comment by saltgen** [comment]
> > Shall we still go ahead with `int` for `max_io` and IOPS value?
> 
> Yes, it should be `int` for both.
> 
> > That said am I using the wrong multiplier i.e. 100. thinking Let me check with Pau
> 
> +1 for checking with Pau

@kgaikwad Thanks, pushed changes here for the multiplier, in-place tests run fine, manually tested as well :+1:

**Review by kgaikwad — APPROVED** [review]
LGTM :+1:

**Pull request merged**
