### PR TITLE
RHIROS-781 optimize /is_configured db queries

### PR DESCRIPTION
**Pull request by r14chandra**

### CODE REVIEW

**Review by kgaikwad — APPROVED** [review]

**Comment by kgaikwad** [comment]
@r14chandra  - instead of optimization I see these changes are more specific to code refactoring & query fixing.

**Comment by r14chandra** [comment]
> @r14chandra - instead of optimization I see these changes are more specific to code refactoring & query fixing.

But I have removed `join` which is expensive and used filters instead. Isn't it considered as optimization?

**Comment by kgaikwad** [comment]
> > @r14chandra - instead of optimization I see these changes are more specific to code refactoring & query fixing.
> 
> But I have removed `join` which is expensive and used filters instead. Isn't it considered as optimization?

@r14chandra  - You have made use of subqueries instead of join. Could you share comparative result i.e time taken using existing join vs subqueries?

**Review by saltgen — COMMENTED** [review]
@r14chandra You could use these event functions for query profiling, [here](https://docs.sqlalchemy.org/en/14/faq/performance.html#query-profiling)

Sample result with existing code:

```
2022-09-23 16:15:33,394 - WARNING  - commence_cw_log_streaming - CLOUDWATCH LOGGING - Disabled
 * Serving Flask app "ros.lib.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2022-09-23 16:15:33,396 - INFO  - _log -  * Running on http://0.0.0.0:8082/ (Press CTRL+C to quit)
2022-09-23 16:15:35,623 - DEBUG  - before_cursor_execute - Start Query: SELECT count(*) AS count_1 
FROM (SELECT systems.id AS systems_id 
FROM systems JOIN performance_profile ON performance_profile.system_id = systems.id JOIN rh_accounts ON rh_accounts.id = systems.tenant_id 
WHERE rh_accounts.org_id = %(org_id_1)s) AS anon_1
2022-09-23 16:15:35,624 - DEBUG  - after_cursor_execute - Query Complete!
2022-09-23 16:15:35,624 - DEBUG  - after_cursor_execute - Total Time: 0.001181
2022-09-23 16:15:35,625 - DEBUG  - before_cursor_execute - Start Query: SELECT count(*) AS count_1 
FROM (SELECT systems.id AS systems_id 
FROM systems JOIN performance_profile ON performance_profile.system_id = systems.id JOIN rh_accounts ON rh_accounts.id = systems.tenant_id 
WHERE rh_accounts.org_id = %(org_id_1)s AND performance_profile.number_of_recommendations > %(number_of_recommendations_1)s) AS anon_1
2022-09-23 16:15:35,626 - DEBUG  - after_cursor_execute - Query Complete!
2022-09-23 16:15:35,626 - DEBUG  - after_cursor_execute - Total Time: 0.000391
2022-09-23 16:15:35,627 - DEBUG  - before_cursor_execute - Start Query: SELECT count(*) AS count_1 
FROM (SELECT systems.id AS systems_id 
FROM systems JOIN performance_profile ON performance_profile.system_id = systems.id JOIN rh_accounts ON rh_accounts.id = systems.tenant_id 
WHERE rh_accounts.org_id = %(org_id_1)s AND systems.state = %(state_1)s) AS anon_1
2022-09-23 16:15:35,627 - DEBUG  - after_cursor_execute - Query Complete!
2022-09-23 16:15:35,627 - DEBUG  - after_cursor_execute - Total Time: 0.000520
2022-09-23 16:15:35,628 - INFO  - _log - 127.0.0.1 - - [23/Sep/2022 16:15:35] "GET /api/ros/v1/is_configured?order_by=max_io&order_how=DESC HTTP/1.1" 200 -
```

**Comment by ShivamPandya** [comment]
@r14chandra  Sorry for the delay in posting observations. PR looks good to me. It is observed that the performance has been improved in API calls (~12% improvement)

**Pull request merged**
