### PR TITLE
RHIROS-471 | ROS Base Image update - ubi8/ubi-minimal

### PR DESCRIPTION
**Pull request by saltgen**
### Changes:
1. `Dockerfile` changes

### Reasons:
1. An official and minimal image is preferable
2. Helps with faster mitigation of security concerns

### Additional:

A sample image has been pushed at `quay.io/sdutta/ros_base_ubi8_api:latest`
Awaiting security analysis on the same, currently queued.

### Testing:
Here's a version of the source code with the updated Dockerfile, along with a docker-compose file
for the ease of testing.

[ros_base_ubi8.zip](https://github.com/RedHatInsights/ros-backend/files/8832276/ros_base_ubi8.zip)

The idea is to spin up an API container successfully, then

- Check if the urls are responsive
- Exec into the container and check if any insecure packages are available in the same

Steps:

1. Unzip the file
2. `cd ros_base_ubi8/`
3. `docker-compose up --build`

Container should be ready now.

**Note**: 75% of the security cards are linked to the base image update JIRA card, and steps used to verify the same has also been shared in each card.

### CODE REVIEW

**Comment by saltgen** [comment]
Needs #196 changes merged for `ci.int.devshift.net PR build`

**Comment by saltgen** [comment]
Looks like ci.int job failure is due to the default timeout of 600 secs on `pr_check.sh`, discussing internally

**Comment by kgaikwad** [comment]
@saltgen - could you please rebase this branch and update?

**Comment by saltgen** [comment]
> @saltgen - could you please rebase this branch and update?

@kgaikwad Done and pushed!

**Comment by kgaikwad** [comment]
@saltgen  - Multiple tests are failing with exception `wait_for.TimedOutError`. Could you please check the details?
@mayurilahane - any pointers ^^?

**Comment by ShivamPandya** [comment]
@kgaikwad It seems like an issue with archives. Passing rate on stage is 95% but things are failing on prod. I am looking into it.

**Comment by saltgen** [comment]
@patilsuraj767 Changes should be good for review now, I'll target the Pipfile updates in a different MR.

**Comment by kgaikwad** [comment]
@ShivamPandya and @saltgen  - What is the status on this PR in terms of EE testing? Any blockers/concerns?

**Comment by ShivamPandya** [comment]
@kgaikwad Looks good to me, we can go ahead with this.

**Comment by kgaikwad** [comment]
@ShivamPandya @digitronik -
Previous [job](https://ci.int.devshift.net/job/RedHatInsights-ros-backend-pr-check/287/) failed with below error - 

```
10:56:59 Traceback (most recent call last):
10:56:59   File "/var/lib/jenkins/workspace/RedHatInsights-ros-backend-pr-check/.bonfire_venv/lib64/python3.6/site-packages/requests/models.py", line 910, in json
10:56:59     return complexjson.loads(self.text, **kwargs)
10:56:59   File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
10:56:59     return _default_decoder.decode(s)
10:56:59   File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
10:56:59     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
10:56:59   File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
10:56:59     raise JSONDecodeError("Expecting value", s, err.value) from None
10:56:59 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I re-triggered the jobs to confirm ^^ above error. It doesn't seem relevant to PR change.

**Comment by kgaikwad** [comment]
Now it's green! Merging this PR :boom::rocket:
Thank you @saltgen for the change & @ShivamPandya  for testing.

**Pull request merged**
